### PR TITLE
Create auth API

### PR DESCRIPTION
**Pull request by andranugraha**
Did you write good & comprehensive specs? ⭐️
no
What's this PR do ? ⭐️
create login, logout, register, forgot and reset password API. customize model and migration to optimize auth. add mail component
What are the relevant tickets ? ⭐️
https://www.notion.so/prawito/Auth-API-Register-Login-Logout-Forgot-Password-11cdaa8566024b4dbd962cac44553568
Any deployment note (migrations, new envs, rake tasks, cron) ?
run php artisan migrate to alter database
Screenshots (if appropriate)
image
image
image
image
image

Documentation link
https://documenter.getpostman.com/view/14101355/U16qJ3aj

### CODE REVIEW

**Comment by andranugraha** [comment]
run composer require doctrine/dbal before migrate

**Comment by andranugraha** [comment]
add to env
MAIL_MAILER=smtp
MAIL_HOST=smtp.googlemail.com
MAIL_PORT=465
MAIL_USERNAME=glints007.noreply@gmail.com
MAIL_PASSWORD=glints007
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=noreply-academy@glints.com
MAIL_FROM_NAME='Glints Academy'

**Review by rahmatullah5 — COMMENTED** [review]
Can you create the API documentation too and put the link on the PR description?

**Comment by andranugraha** [comment]
done ka

**Review by chaterinamf — APPROVED** [review]

**Pull request merged**
